### PR TITLE
prompt warning message on allocating new FIP

### PR DESCRIPTION
**Pull request by carmark**
### Test Result

```
[lei@h8s-single hypercli]$ hyper/hyper fip allocate 1
Please note that Floating IP (FIP) is billed monthly. The billing begins when a new IP is allocated, ends when it is released. Partial month is treated as a entire month. Do you want to continue? [y/n]: n
[lei@h8s-single hypercli]$ hyper/hyper fip allocate 1
Please note that Floating IP (FIP) is billed monthly. The billing begins when a new IP is allocated, ends when it is released. Partial month is treated as a entire month. Do you want to continue? [y/n]: y
Error response from daemon: No more quota for use, please delete some, or apply more
[lei@h8s-single hypercli]$
```

### CODE REVIEW

**Comment by Gnep** [comment]
@carmark use the following message:
```
Please note that Floating IP (FIP) is billed monthly. The billing begins when a new IP is allocated, ends when it is released. Partial month is treated as a entire month. Do you want to continue? [y/n]: y
```

**Comment by carmark** [comment]
@Gnep no default value, it will continue to show the prompt message if the user didn't input anything.  Also, you can use new option `-f` or `--force` to allocate new FIP, it will not show that warn message.

**Comment by gnawux** [comment]
I think `-y|--yes` is better than `-f|--force` for the Yes/No question.

**Comment by carmark** [comment]
@gnawux agreed, fixed.

**Pull request merged**
